### ISSUE TITLE
Cant finishe async setup error

### ISSUE THREAD

**Issue by MTThor** [HomeAssistant-Mods/home-assistant-miele#78] opened 2021-10-31 10:08 UTC
I have the following problem, since the update I get this error message. 

I reinstall the module, delete the cache, check DuckDNS, 
nothing helped

Since the update, the entitys remaning time, starttime.  etc. are also gone. 

I reinstall the module x times. Test with beta version 0.9.1 also doesnt work´.

Error message:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 150, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 52, in get_devices
    for home_device in home_devices:
TypeError: 'coroutine' object is not iterable

**Comment by kloknibor** [comment] 2021-11-04 12:04
This error normally relates to your system not retrieving any data from the miele API. Please try your credentials used in homeassistant directly on this page : https://www.miele.com/developer/swagger-ui/ and report back if you can use this API from there or not. If u also cannot use that than ur problem is with your miele account and you will need to contact miele.

**Comment by Phyxsius7** [comment] 2021-11-06 21:29
- Version | core-2021.11.1
- Installation Type | Home Assistant OS

I can confirm the same issue as discribed by MTThor.
I can use the API with Postman and with Miele Swagger-ui, with the same credentials.
Maybe also good to mention is that after fresh install, providing client_id and client_secret, the Miele authentication UI does not pop-up/show. So the access_token and refresh_token is never requested.

**Comment by zwulf1k** [comment] 2021-11-06 22:22
Have the same issue,

https://www.miele.com/developer/swagger-ui/ -- can get device information, all APIs methods work fine.
HA - can't get any inforamation

County Russia

**Comment by Phyxsius7** [comment] 2021-11-20 11:29
@kloknibor
Any ideas as what the cause cause be?
Can I assist and/or provide more information to help analyze this issue further?

**Comment by kloknibor** [comment] 2021-11-26 02:30
@Phyxsius7 Work currently got me swamped... Sorry about that. As soon as I have time I'll look into this and report back here :-) If I'm unable to replicate it I might need some help from you by than.

**Comment by Phyxsius7** [comment] 2022-01-10 18:00
@kloknibor 
Hope you could find the time for this and I am always happy to help. I also see that another inquiry was made here:
https://github.com/HomeAssistant-Mods/home-assistant-miele/issues/95#issue-1096983735

**Comment by Phyxsius7** [comment] 2022-02-22 21:32
Hey @kloknibor 
How you doing these days?
I was wondering if we could continue on fixing this issue?
Or is it already been fix?
Hope to read from you soon.

**Comment by kloknibor** [comment] 2022-03-02 17:18
Should have been fixed by a PR from someone else as far as I'm aware

**Closed as completed** 2022-04-08 12:46 UTC
