### ISSUE TITLE
Sensor Error: Task exception was never retrieved

### ISSUE THREAD

**Issue by FransHalsjes** [HomeAssistant-Mods/home-assistant-miele#103] opened 2022-02-02 10:28 UTC
Since 2012.12.10 the miele integration gives:

````
Logger: homeassistant
Source: custom_components/miele/sensor.py:712
Integration: Miele@home (documentation, issues)
First occurred: 31 januari 2022 13:28:26 (15777 occurrences)
Last logged: 06:50:39

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/miele/sensor.py", line 712, in state
    state_value = self._device["state"][self._key][self._index]["value_raw"]
IndexError: list index out of range

```

**Comment by cpohli** [comment] 2022-02-14 10:05
Getting something similar here:
```
Logger: homeassistant
Source: custom_components/miele/sensor.py:644 
Integration: Miele@home ([documentation](https://github.com/HomeAssistant-Mods/home-assistant-miele), [issues](https://github.com/HomeAssistant-Mods/home-assistant-miele/issues)) 
First occurred: 10:55:40 (92 occurrences) 
Last logged: 11:02:05

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/miele/sensor.py", line 644, in state
    if "currentEnergyConsumption" in device_state["ecoFeedback"]:
TypeError: argument of type 'NoneType' is not iterable
```

and 

```
Logger: homeassistant
Source: custom_components/miele/sensor.py:657 
Integration: Miele@home ([documentation](https://github.com/HomeAssistant-Mods/home-assistant-miele), [issues](https://github.com/HomeAssistant-Mods/home-assistant-miele/issues)) 
First occurred: 10:55:40 (78 occurrences) 
Last logged: 11:02:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/miele/sensor.py", line 657, in state
    if "currentWaterConsumption" in device_state["ecoFeedback"]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kloknibor** [comment] 2022-02-14 18:14
With version Home Assistant 2022.2.6 I am unable to reproduce any of these errors. What devices do you guys have? Did you guys disable devices?

**Comment by cpohli** [comment] 2022-02-15 09:24
I'm running on 2022.2.6 as well and using a Miele Dishwasher. It's connected to Miele and seems to work fine in HA. I'm getting correct values on the sensors in HA that I use (progress, finished, warnings etc.).
![SCR-20220216-bpc](https://user-images.githubusercontent.com/32699124/154216249-85d26aca-7230-4bb3-8156-1f8c678b958a.png)

**Comment by cpohli** [comment] 2022-02-15 21:47
I'm also at HA 2022.2.6 and using a Miele Dishwasher. It's connected to Miele servers and the sensors in HA seem to work well (I get data for times, warnings, finished etc.). Nothing is disabled.

**Comment by cpohli** [comment] 2022-03-28 13:29
Any idea here? Something i could help with?
The Error still shows up and i'm wondering (after a fresh reboot) is the counting correct?
That would be over 2000 times in roughly three hours?

```
Logger: homeassistant
Source: custom_components/miele/sensor.py:644
Integration: Miele@home ([documentation](https://github.com/HomeAssistant-Mods/home-assistant-miele), [issues](https://github.com/HomeAssistant-Mods/home-assistant-miele/issues))
First occurred: 12:51:38 (2167 occurrences)
Last logged: 15:26:22
```

**Comment by kloknibor** [comment] 2022-04-08 12:47
duplicate of #86

**Closed as completed by kloknibor** 2022-04-08 12:47 UTC
